'use strict';

var keyMirror = require('keymirror');

module.exports = keyMirror({
  ACTION_CREATE: null,
  ACTION_COMPLETE: null,
  ACTION_DESTROY: null,
  ACTION_DESTROY_COMPLETED: null,
  ACTION_TOGGLE_COMPLETE_ALL: null,
  ACTION_UNDO_COMPLETE: null,
  ACTION_UPDATE_TEXT: null,
  ACTION_SEARCH_INIT: null,
  ACTION_SEARCH_TERM_CHANGE: null,
  ACTION_SEARCH_RELATED_TOPIC: null,
  ACTION_SEARCH_RELATED_COLLECTION: null,
  ACTION_TOGGLE_HAMBURGER:null,
  ACTION_CHANGE_USER:null,
  ACTION_CHANGE_VIEW:null,
  ACTION_PROGRAM_SEARCH: null,
  ACTION_GET_MENTIONS: null,

  CHANGE_EVENT : null,
  CHANGE_SEARCH_TERM_EVENT : null,
  CHANGE_RELATED_TOPICS_EVENT : null,
  CHANGE_RELATED_COLLECTIONS_EVENT : null,
  TOGGLE_HAMBURGER_EVENT : null,
  CHANGE_USER_EVENT : null,
  CHANGE_VIEW_EVENT : null,
  CHANGE_PROGRAM_SEARCH_EVENT : null,
  CHANGE_MENTIONS_EVENT : null,


  APP_BROADCASTER:null,
  APP_CONSUMER:null,


  VIEW_MENTION_LIST:null,
  VIEW_PROGRAM_LIST:null,
  VIEW_TOP_TRENDS_LIST:null,
  VIEW_TRENDING_SEARCH_TERMS_LIST:null
});